<?php


/**
 * Skeleton subclass for performing query and update operations on the 'bookmark' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/15/12 13:35:34
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BookmarkPeer extends BaseBookmarkPeer
{
	public static function doSelectWithSearch($search, Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;

		$search = str_replace('%', '', $search);

		if ($search)
		{
			$s = '%' . $search . '%';

			// $s = '%' . str_replace(array('=', '_', '%'), array('==', '=_', '=%'), $search) . '%';
			// "name LIKE '%$escapedname%' ESCAPE '='"

			$critcopy->add(
				$critcopy->
					getNewCriterion(self::TITLE, $s, Criteria::LIKE)->
						addOr($critcopy->getNewCriterion(self::INFO, $s, Criteria::LIKE))->
						addOr($critcopy->getNewCriterion(self::URL, $s, Criteria::LIKE))
			);
		}

		return self::doSelect($critcopy, $con);
	}
} // BookmarkPeer
