<?php


/**
 * Skeleton subclass for performing query and update operations on the 'vote' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/15/12 13:39:27
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VotePeer extends BaseVotePeer
{
	public static function getVoteBookmarksByUser($Bookmarks, $user_id)
	{
		if (!$user_id || !$Bookmarks) return array();

		$ids = array();
		foreach ($Bookmarks as $b) $ids[] = $b->getId();

		$criteria = new Criteria();
		$criteria->
			add(self::USER_ID, $user_id, Criteria::EQUAL)->
			add(self::BOOKMARK_ID, $ids, Criteria::IN);

		$votes = array();

		foreach(self::doSelect($criteria) as $v)
			$votes[$v->getBookmarkId()] = $v->getVote();

		return $votes;
	}
} // VotePeer
