generator:
  class: sfPropelBoostrapGenerator
  param:
    model_class:           Bookmark
    theme:                 sfBootstrapTheme
    non_verbose_templates: true
    with_show:             false
    singular:              Bookmark
    plural:                Bookmarks
    route_prefix:          bookmark
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
