propel:
  bookmark:
    id:           ~
    user_id:      { type: integer, foreignTable: sf_guard_user, foreignReference: id }
    title:        { type: varchar(255), required: true, index: true }
    info:         { type: longvarchar }
    url:          { type: varchar(255) }
    rating:       { type: integer, default: 0, index: true }
    vote_good:    { type: integer, default: 0 }
    vote_bad:     { type: integer, default: 0 }
    created_at:   ~
    updated_at:   ~

  category:
    _attributes:  { isI18N: true, i18nTable: category_i18n }
    id:           ~
    created_at:   ~
    updated_at:   ~

  category_i18n:
    id:           { type: integer, required: true, primaryKey: true, foreignTable: category, foreignReference: id, onDelete: cascade }
    culture:      { isCulture: true, type: char, size: 2, required: true, primaryKey: true }
    title:        { type: varchar(255), required: true, index: true }

  bookmark_category:
    bookmark_id:  { type: integer, foreignTable: bookmark, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    category_id:  { type: integer, foreignTable: category, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }

  vote:
    user_id:      { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    bookmark_id:  { type: integer, foreignTable: bookmark, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    vote:         { type: boolean,  required: true }